Загрузка необходимых библиотек

In [1]:
import pandas as pd
pd.options.display.max_columns = 1000

Открытие датасета

In [2]:
df = pd.read_csv('dfMoscow4(demo).csv')
df

,Unnamed: 0,properties.id,properties.point.lat,properties.point.long,properties.region,properties.address,properties.category,properties.severity,properties.dead_count,properties.parent_region,properties.participants_count,Участие пешеходов,Водитель,Иной вид ДТП,Наезд на велосипедиста,Наезд на пешехода,Наезд на препятствие,Наезд на стоящее ТС,Опрокидывание,Падение пассажира,Столкновение,Съезд с дороги,Легкий,С погибшими,Тяжёлый,Кол-во ДТП по данному адресу,Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве,Широта,Долгота
0,0,1539006,55.580831,37.574133,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",Наезд на стоящее ТС,Легкий,0,Москва,2,0,Мужчина,0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
1,1,1576161,55.578187,37.585258,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",Столкновение,Легкий,0,Москва,3,0,Мужчина,0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
2,2,1558814,55.577581,37.587780,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",Столкновение,Легкий,0,Москва,2,0,Женщина,0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
3,3,1535217,55.577714,37.586975,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",Столкновение,Легкий,0,Москва,4,0,Мужчина,0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
4,4,1553333,55.968300,37.963100,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",Столкновение,Тяжёлый,0,Москва,3,0,Мужчина,0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37241,37241,2165411,55.737066,38.073206,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",Столкновение,Тяжёлый,0,Московская область,3,0,Мужчина,0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37242,37242,2161878,55.256000,36.254100,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",Столкновение,Тяжёлый,0,Московская область,3,0,Мужчина,0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37243,37243,2140674,55.740600,38.072800,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",Столкновение,Тяжёлый,0,Московская область,2,0,Мужчина,0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37244,37244,2158867,55.735919,38.074225,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",Опрокидывание,С погибшими,1,Московская область,1,0,Мужчина,0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37245,37245,2143336,55.735000,38.075600,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",Столкновение,Тяжёлый,0,Московская область,2,0,Мужчина,0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206

In [3]:
df = df.drop(['Unnamed: 0'], axis = 1)
df = df.drop(['properties.id'], axis = 1)
df = df.drop(['properties.point.lat'], axis = 1)
df = df.drop(['properties.point.long'], axis = 1)
df = df.drop(['properties.category'], axis = 1)
df = df.drop(['properties.severity'], axis = 1)
df = df.drop(['properties.dead_count'], axis = 1)
df = df.drop(['properties.parent_region'], axis = 1)
df = df.drop(['properties.participants_count'], axis = 1)
df = df.drop(['Участие пешеходов'], axis = 1)
df = df.drop(['Водитель'], axis = 1)
df

,properties.region,properties.address,Иной вид ДТП,Наезд на велосипедиста,Наезд на пешехода,Наезд на препятствие,Наезд на стоящее ТС,Опрокидывание,Падение пассажира,Столкновение,Съезд с дороги,Легкий,С погибшими,Тяжёлый,Кол-во ДТП по данному адресу,Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве,Широта,Долгота
0,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
1,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
2,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
3,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
4,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37241,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37242,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37243,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37244,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206
37245,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206

In [4]:
df.drop_duplicates(subset = 'properties.address', inplace = True)

In [5]:
df.reset_index(drop=True)

,properties.region,properties.address,Иной вид ДТП,Наезд на велосипедиста,Наезд на пешехода,Наезд на препятствие,Наезд на стоящее ТС,Опрокидывание,Падение пассажира,Столкновение,Съезд с дороги,Легкий,С погибшими,Тяжёлый,Кол-во ДТП по данному адресу,Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве,Широта,Долгота
0,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
1,Ярославский,"г Москва, ш Ярославское, 1",0,1,24,16,2,2,8,66,0,100,6,13,10,0.000095,55.871109,37.711612
2,Восточное Измайлово,"г Москва, Московская кольцевая автомобильная д...",2,0,1,3,6,0,1,9,0,17,2,3,22,0.000210,55.800340,37.839965
3,Строгино,"г Москва, Московская кольцевая автомобильная д...",0,0,0,1,3,0,0,16,0,16,0,4,20,0.000191,55.797798,37.380348
4,Новокосино,"г Москва, ш Носовихинское, 1км",0,0,0,1,1,0,0,4,0,5,1,0,6,0.000057,55.744075,37.843950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4076,Балашиха,"г Балашиха, ул Звездная, 4",0,1,5,0,0,0,0,0,0,4,0,2,6,0.000057,55.821261,37.835578
4077,Балашиха,"г Балашиха, А-103 Щелковское шоссе Москва - Ще...",0,0,3,0,0,0,1,6,0,5,0,5,10,0.000095,55.825600,37.890800
4078,Балашиха,"г Балашиха, ул Текстильщиков, 15",0,0,1,0,0,0,0,6,0,4,0,3,7,0.000067,55.812436,37.965840
4079,Балашиха,"г Балашиха, MКАД-ЖЕЛЕЗНОДОРОЖНЫЙ-ЛИКИНО-ДУЛЕВО...",0,0,2,0,1,0,0,5,0,3,1,4,8,0.000076,55.753091,38.096150
4080,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4081 entries, 0 to 37241
Data columns (total 18 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   properties.region                                            4081 non-null   object
 1   properties.address                                           4081 non-null   object
 2   Иной вид ДТП                                                 4081 non-null   int64
 3   Наезд на велосипедиста                                       4081 non-null   int64
 4   Наезд на пешехода                                            4081 non-null   int64
 5   Наезд на препятствие                                         4081 non-null   int64
 6   Наезд на стоящее ТС                                          4081 non-null   int64
 7   Опрокидывание                                                4081 non-null   int64
 8   Падение пассажира                                            4081 non-null   int64
 9   Столкновение                                                 4081 non-null   int64
 10  Съезд с дороги                                               4081 non-null   int64
 11  Легкий                                                       4081 non-null   int64
 12  С погибшими                                                  4081 non-null   int64
 13  Тяжёлый                                                      4081 non-null   int64
 14  Кол-во ДТП по данному адресу                                 4081 non-null   int64
 15  Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве  4081 non-null   float64
 16  Широта                                                       4081 non-null   float64
 17  Долгота                                                      4081 non-null   float64
dtypes: float64(3), int64(13), object(2)
memory usage: 605.8+ KB

In [7]:
df.rename(columns={'properties.region': 'Район'}, inplace=True)
df.rename(columns={'properties.address': 'Адрес'}, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4081 entries, 0 to 37241
Data columns (total 18 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Район                                                        4081 non-null   object
 1   Адрес                                                        4081 non-null   object
 2   Иной вид ДТП                                                 4081 non-null   int64
 3   Наезд на велосипедиста                                       4081 non-null   int64
 4   Наезд на пешехода                                            4081 non-null   int64
 5   Наезд на препятствие                                         4081 non-null   int64
 6   Наезд на стоящее ТС                                          4081 non-null   int64
 7   Опрокидывание                                                4081 non-null   int64
 8   Падение пассажира                                            4081 non-null   int64
 9   Столкновение                                                 4081 non-null   int64
 10  Съезд с дороги                                               4081 non-null   int64
 11  Легкий                                                       4081 non-null   int64
 12  С погибшими                                                  4081 non-null   int64
 13  Тяжёлый                                                      4081 non-null   int64
 14  Кол-во ДТП по данному адресу                                 4081 non-null   int64
 15  Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве  4081 non-null   float64
 16  Широта                                                       4081 non-null   float64
 17  Долгота                                                      4081 non-null   float64
dtypes: float64(3), int64(13), object(2)
memory usage: 605.8+ KB

In [9]:
df

,Район,Адрес,Иной вид ДТП,Наезд на велосипедиста,Наезд на пешехода,Наезд на препятствие,Наезд на стоящее ТС,Опрокидывание,Падение пассажира,Столкновение,Съезд с дороги,Легкий,С погибшими,Тяжёлый,Кол-во ДТП по данному адресу,Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве,Широта,Долгота
0,Чертаново Южное,"г Москва, Московская кольцевая автомобильная д...",0,0,0,0,3,0,0,11,0,9,0,5,14,0.000133,55.579467,37.583253
14,Ярославский,"г Москва, ш Ярославское, 1",0,1,24,16,2,2,8,66,0,100,6,13,10,0.000095,55.871109,37.711612
24,Восточное Измайлово,"г Москва, Московская кольцевая автомобильная д...",2,0,1,3,6,0,1,9,0,17,2,3,22,0.000210,55.800340,37.839965
46,Строгино,"г Москва, Московская кольцевая автомобильная д...",0,0,0,1,3,0,0,16,0,16,0,4,20,0.000191,55.797798,37.380348
66,Новокосино,"г Москва, ш Носовихинское, 1км",0,0,0,1,1,0,0,4,0,5,1,0,6,0.000057,55.744075,37.843950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37210,Балашиха,"г Балашиха, ул Звездная, 4",0,1,5,0,0,0,0,0,0,4,0,2,6,0.000057,55.821261,37.835578
37216,Балашиха,"г Балашиха, А-103 Щелковское шоссе Москва - Ще...",0,0,3,0,0,0,1,6,0,5,0,5,10,0.000095,55.825600,37.890800
37226,Балашиха,"г Балашиха, ул Текстильщиков, 15",0,0,1,0,0,0,0,6,0,4,0,3,7,0.000067,55.812436,37.965840
37233,Балашиха,"г Балашиха, MКАД-ЖЕЛЕЗНОДОРОЖНЫЙ-ЛИКИНО-ДУЛЕВО...",0,0,2,0,1,0,0,5,0,3,1,4,8,0.000076,55.753091,38.096150
37241,Балашиха,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",0,0,0,0,0,1,0,4,0,0,1,4,5,0.000048,55.735919,38.073206

In [10]:
df = df[['Адрес', 'Район', 'Кол-во ДТП по данному адресу' , 'Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве', 'Легкий', 'Тяжёлый' , 'С погибшими' , 'Иной вид ДТП', 'Наезд на велосипедиста', 'Наезд на пешехода' , 'Наезд на препятствие' , 'Наезд на стоящее ТС', 'Опрокидывание', 'Падение пассажира' , 'Столкновение' , 'Съезд с дороги', 'Широта', 'Долгота']]

In [11]:
df

,Адрес,Район,Кол-во ДТП по данному адресу,Отношение кол-ва ДТП по данному адресу ко всем ДТП в Москве,Легкий,Тяжёлый,С погибшими,Иной вид ДТП,Наезд на велосипедиста,Наезд на пешехода,Наезд на препятствие,Наезд на стоящее ТС,Опрокидывание,Падение пассажира,Столкновение,Съезд с дороги,Широта,Долгота
0,"г Москва, Московская кольцевая автомобильная д...",Чертаново Южное,14,0.000133,9,5,0,0,0,0,0,3,0,0,11,0,55.579467,37.583253
14,"г Москва, ш Ярославское, 1",Ярославский,10,0.000095,100,13,6,0,1,24,16,2,2,8,66,0,55.871109,37.711612
24,"г Москва, Московская кольцевая автомобильная д...",Восточное Измайлово,22,0.000210,17,3,2,2,0,1,3,6,0,1,9,0,55.800340,37.839965
46,"г Москва, Московская кольцевая автомобильная д...",Строгино,20,0.000191,16,4,0,0,0,0,1,3,0,0,16,0,55.797798,37.380348
66,"г Москва, ш Носовихинское, 1км",Новокосино,6,0.000057,5,0,1,0,0,0,1,1,0,0,4,0,55.744075,37.843950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37210,"г Балашиха, ул Звездная, 4",Балашиха,6,0.000057,4,2,0,0,1,5,0,0,0,0,0,0,55.821261,37.835578
37216,"г Балашиха, А-103 Щелковское шоссе Москва - Ще...",Балашиха,10,0.000095,5,5,0,0,0,3,0,0,0,1,6,0,55.825600,37.890800
37226,"г Балашиха, ул Текстильщиков, 15",Балашиха,7,0.000067,4,3,0,0,0,1,0,0,0,0,6,0,55.812436,37.965840
37233,"г Балашиха, MКАД-ЖЕЛЕЗНОДОРОЖНЫЙ-ЛИКИНО-ДУЛЕВО...",Балашиха,8,0.000076,3,4,1,0,0,2,0,1,0,0,5,0,55.753091,38.096150
37241,"г Балашиха, МКАД-Крутицы-Железнодорожный-Ликин...",Балашиха,5,0.000048,0,4,1,0,0,0,0,0,1,0,4,0,55.735919,38.073206

In [12]:
df.to_csv('dfMoscow5.csv')